locator_shutdown = ("xpath","//*[contains(@class,'icon-shutdown')]")#双十一弹窗的关闭按钮
locator_class = ("xpath","//*[contains(@class,'icon-footer2')]")#分类
locator_firstGoods = ("xpath","//*[@class='image-con'][1]")#进入分类列表的第一个元素
locator_buy = ("xpath","//*[text()='立即购买']")#"立即购买"按钮
locator_me = ("xpath","//*[@id='icon-me']")#我的
locator_login = ("xpath","//*[@class='btn']")#点击"我的"出现的登录按钮
locator_username = ("id","username")#用户名
locator_password = ("id","password")#密码
locator_login2 = ("xpath","//*[@class='login-btn'][1]")#登录按钮
locator_wechat = ("xpath","//*[contains(@class,'wechat')]")#微信支付按钮
locator_scan = ("xpath","//*[@class='pay-pc-con']")#微信二维码界面